/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
module

public import CenteredMaximal.Ball.PenaltyCompactness
public import CenteredMaximal.Ball.PenaltyEnergyBound

/-!
# A bounded weak limit of capped ball penalties

Choose penalty parameters tending to zero, solve the capped penalized equations, and pass to
weak limits of the states and their density terms.
-/

@[expose] public section

noncomputable section

set_option maxHeartbeats 800000

open InnerProductSpace MeasureTheory Metric Filter Topology
open scoped RealInnerProductSpace NNReal ENNReal

namespace CenteredMaximal.Ball.DirichletSobolev

variable {n : ℕ}

/-- A positive penalty parameter tending to zero. -/
def ballPenaltyEpsilon (k : ℕ) : ℝ := ((k + 1 : ℕ) : ℝ)⁻¹

theorem ballPenaltyEpsilon_pos (k : ℕ) : 0 < ballPenaltyEpsilon k := by
  unfold ballPenaltyEpsilon
  positivity

/-- The density generated by the negative-part penalty. -/
def ballPenaltyDensity
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (k : ℕ) (U : H01 (ball center R)) : L2D (ball center R) :=
  (ballPenaltyEpsilon k)⁻¹ • Lp.negPart (valueEmbedding (ball center R) U)

/-- Select one capped solution for each penalty parameter, with one common state norm bound. -/
theorem exists_ball_penalized_sequence
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (f : L2D (ball center R)) (κ : ℝ) (hκ : 0 ≤ κ)
    (hf : ∀ᵐ x ∂(volume.restrict (ball center R)), 0 ≤ f x) :
    ∃ C : ℝ, ∃ U : ℕ → H01 (ball center R),
      (∀ k, ‖U k‖ ≤ C) ∧
      (∀ k, ∀ V : H01 (ball center R),
        laplaceBilin (ball center R) (U k) V =
          l2Functional (ball center R) f V -
            κ * l2Functional (ball center R) (ballUnitL2 center R) V +
            ⟪ballPenaltyDensity center R k (U k),
              valueEmbedding (ball center R) V⟫_ℝ) ∧
      (∀ k, ∀ᵐ x ∂(volume.restrict (ball center R)),
        (ballPenaltyDensity center R k (U k)) x ≤ κ) := by
  obtain ⟨C, hC⟩ := exists_uniform_ball_penalized_norm_bound center R f κ
  have hsol (k : ℕ) := exists_ball_penalized_solution_capped center R f κ
    (ballPenaltyEpsilon k) hκ (ballPenaltyEpsilon_pos k) hf
  choose U hUweak hUcap using hsol
  refine ⟨C, U, (fun k => hC (ballPenaltyEpsilon k) (ballPenaltyEpsilon_pos k)
    (U k) (hUweak k)), ?_, ?_⟩
  · intro k V
    have h := hUweak k V
    simpa only [ballPenaltyDensity, real_inner_smul_left] using h
  · intro k
    filter_upwards [hUcap k,
      Lp.coeFn_smul (ballPenaltyEpsilon k)⁻¹
        (Lp.negPart (valueEmbedding (ball center R) (U k)))] with x hx hsmul
    simpa only [ballPenaltyDensity, hsmul, Pi.smul_apply, smul_eq_mul] using hx

end CenteredMaximal.Ball.DirichletSobolev
